### PR TITLE
Fix LT-18379:Build and use 64bit versions of SIL Encoding Converters

### PR DESCRIPTION
**Pull request by vkarthim**
* Changed project platform as AnyCPU

### CODE REVIEW

**Comment by devosb** [comment]
TECkit now has a 64-bit Windows build, in addition to the existing 32-bit Windows build (and the also existing 32 and 64 bit Linux builds). Download at http://scripts.sil.org/TECkitDownloads which also points to https://github.com/silnrsi/teckit/releases which has additional files for downloading .

**Comment by papeh** [comment]
@devosb I don't think we fully understand your comment. Are you saying the `encoding-converters-core` build process needs to download the 64-bit TECkit binaries in addition to the 32-bit binaries? What other changes or testing are needed before this can be merged? Thank you in advance for your help.

**Comment by devosb** [comment]
In the description for LT-18379 it says "Any dependencies will also need to have 64bit versions". So, yes, the 64-bit Windows TECkit binaries will need to be downloaded when doing a 64 bit build of `encoding-converters-core`.  You will need to change the runtime files that are distributed with the TECkit Windows build, an overview of these changes is at https://github.com/silnrsi/teckit/blob/master/README with more details in the long comment in https://github.com/silnrsi/teckit/blob/master/build-windows-package.sh

**Comment by jasonleenaylor** [comment]
This PR was superceded by one targeting a new branch. All the 64bit changes needed will happen there.

**Pull request closed without merging**
