### PR TITLE
Revise, add CI, and improve for use from flatpak FieldWorks

### PR DESCRIPTION
**Pull request by marksvc**
The new github action builds on both Linux and Windows for configurations Debug and Release. Though unit test running is not performed across all of them.

I think the problem #if'd out in RunTests/Main.cs must be a problem on Windows as well as Linux. Although the problem #if'd out in TestEncConverters.cs may only be an issue on Linux at this time.

I'm not really wanting to present each of these commits together in a group. I would prefer to present many of them for review independently, but the process is a lot easier if I keep them in a group so here they are.

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I have a question about the #if TODO sections. Did those work without flatpack before?

**Comment by marksvc** [comment]
@jasonleenaylor No. The beginning of this PR is just trying to fix the Linux build and tests after some recent commits to master. 
IIRC: 
A connection was made to some ICU code (IcuBreakIteratorEncConverter) that was hooked up for Windows but still needs hooked up for Linux. It wasn't quickly clear how I might do that. 
And there was a refactor of TestPyScriptEncConverters that I don't think will work on Windows or Linux until it gets some more attention. 
And the #if's switch off those two sections.

**Review by jasonleenaylor — APPROVED** [review]

**Comment by bobeaton** [comment]
sorry to be late to the game. Is there anything I can help with? e.g. IcuBreakIterator, etc. I have a number of changes as well that I want to merge in and it might be good to do that with you, Mark, so we can see how they affect the linux build. contact me at: bob_eaton@sall.com (or skype: lexhead) if you want to try to set up a time

**Comment by marksvc** [comment]
@bobeaton That sounds great.

If you remove `#if TODO_RESOLVE_TO_NEW_LOCATION` and its `#endif`, I'm expecting that src/RunTests/Main.cs will fail on Windows. It looked like only part of a refactor/move was done and that more needs to take place for this to be able to find what it needs. Maybe that's done but just not sent to the repository yet. (Or maybe it's just failing on Linux.)

You could push your work to a branch, whether in this repo or a fork, and I can check it out and see if it builds or has any test regressions. 

Actually, I haven't confirmed that this is working, but with the Github Action to build+test, if you make a PR against this repository you ought to be able to see ahead of time if it builds on both Windows and Linux, so that's handy. 

I'll contact you to set up a time.

**Pull request merged**
