### PR TITLE
Update to TECkit 2.5.11 released in 2021

### PR DESCRIPTION
**Pull request by devosb**

### CODE REVIEW

**Comment by papeh** [comment]
Is there a way to do this without checking in all these binaries? NuGet or (if we must) TeamCity downloads?

**Comment by devosb** [comment]
I don't think the project (encoding-converters-core) is setup to pull in TECkit via NuGet. If it is, I am happy to use NuGet. I don't think TECkit is built on TeamCity, it is built using [GHA](https://github.com/silnrsi/teckit/actions).

**Comment by papeh** [comment]
Ah. Since GHA hosts artifacts as a zip file, we'd need to add a  build step to unzip after downloading, but the artifacts are already publicly available at https://github.com/silnrsi/teckit/suites/4670826419/artifacts/127079356 or similar.

**Comment by papeh** [comment]
If downloading as part of the build process is a hurdle we don't want to clear now, we could save that for a future commit.

**Comment by bobeaton** [comment]
> If downloading as part of the build process is a hurdle we don't want to clear now, we could save that for a future commit.

I'd be happy to try to make that work, but not until early April when I get back to the states. 

@papeh , do you have another solution for the "runs-on: windows-2019" vs. "runs-on: windows-latest" issue causing the windows builds to fail for not having the proper .net framework installed (due to their switch to VS 2022 as windows latest)?

**Comment by bobeaton** [comment]
ok, I'll change this to windows-2019 for now and if that all works, merge the change

**Pull request merged**
